title: Vighnesh Hareesh Nayak
email: vighneshnayak203@gmail.com
description: Portfolio showcasing my projects, skills, and achievements.
url: "https://Kugelblitz25.github.io/Kugelblitz25"
github_username: Kugelblitz25
theme: slate
